matrix:
  include:

    - language: node_js
      node_js: "10"
      script:
        - npm run build

    - language: java
      jdk: oraclejdk11
      script:
        - mvn clean compile assembly:single